version: '3'
services:
  app:
    build:
      context: .
    container_name: vps-project-container
    ports:
      - "5000:5000"
    env_file:
      - .env
    networks:
      - vps-network
    restart: always
    labels:
      - "com.example.monitoring=true"

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - vps-network
    restart: always

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - vps-network
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
    restart: always

networks:
  vps-network:
    driver: bridge
