name: Deploy to VPS

on:
  push:
    branches:
      - main
 
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v3

      - name: Se connecter au VPS et déployer
        uses: appleboy/ssh-action@master
        with:
          host: 85.31.238.192
          username: thomas
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22666
          script: |
            cd /home/user/vps-project
            git pull origin main
            docker build -t vps-project .
            docker stop vps-project-container || true
            docker rm vps-project-container || true
            docker run -d --name vps-project-container -p 5000:5000 --env-file .env vps-project
